### ISSUE TITLE
Log In button notaion

### ISSUE THREAD

**Issue by voiciphil** [esfiddle/site#93]
### Type of issue

- [x] Bug
- [ ] Feature/Enhancement
- [ ] Question

### Description

The current notation of the login button is 'Log in'. It appears in two lines in site. I want to fix it to 'Login' to show it in a line. And the logout button next to it is notated 'Logout'. I want to make them uniform.

**Comment by collinmesser** [comment]
@voiciphil Thank you for your interest in fixing bugs with ESFiddle. As I mentioned on your PR this isn't an actual bug as "Log In" is the correct grammar here. I would call it a bug that the text wraps to the second line though. But I know that this issue is taken care of on the branch https://github.com/esfiddle/site/tree/issue-75 which should get merged in within a day or two.
